# Generated by Django 4.2.4 on 2023-08-29 22:58

from django.db import migrations, models
import django.db.models.deletion
import treasuremap.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('point', treasuremap.fields.LatLongField(max_length=24)),
                ('rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temper', models.FloatField()),
                ('humidity', models.FloatField()),
                ('presure', models.FloatField()),
                ('wind_direction', models.CharField(max_length=50)),
                ('wind_speed', models.FloatField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place')),
            ],
        ),
    ]
