# Generated by Django 4.2.4 on 2023-09-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_weather_presure_weather_date_weather_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_direction',
            field=models.PositiveSmallIntegerField(verbose_name='Направление ветра'),
        ),
    ]
