# Generated by Django 4.2.4 on 2023-09-03 22:54

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_place_title_alter_weather_wind_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Картинка'),
        ),
    ]
